/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package circuitikztool;

/**
 *
 * @author James
 */
public class CurrentSourceBuilder extends javax.swing.JPanel {

    public final static int CURRENT = 0;
    public final static int CONTROLLED_CURRENT = 1;

    int sourceType = -1;

    String componentType;

    private void parseLatexParameters(String input) {
        try {
            try {
                componentType = input.substring(input.indexOf("to[") + 3, input.indexOf(","));
            } catch (IndexOutOfBoundsException e) {
                componentType = input.substring(input.indexOf("to[") + 3, input.indexOf("]"));
            }
            if (componentType.toLowerCase().contains("ci")) {
                sourceType = CONTROLLED_CURRENT; 
            } else if (componentType.toLowerCase().contains("i")) {
                sourceType = CURRENT; 
            } else {
                System.out.println("Could not determine source type from: " + input);
            }

            sourceSelector.setSelectedIndex(sourceType);
            componentLabel.setText(getParameter(input, "l"));
        } catch (Exception e) {
            System.out.println("Failed to parse source component in parseLatexParameters string: " + input + " could not be parsed" + e.getMessage());
        }
    }

    private String getParameter(String text, String parameter) {
        String cleaned = text.replace("to[", "").replace("]", "");
        String[] params = cleaned.split(",");
        for (int a = 0; a < params.length; a++) {
            if (params[a].contains(parameter + "=")) {
                return params[a].replace(parameter + "=", "");
            }
        }
        return "";
    }

    public String getLatexParameters() {
        String ret = "to[";
        switch (sourceSelector.getSelectedIndex()) {
            case CURRENT:
                ret += "I";
                break;
            case CONTROLLED_CURRENT:
                ret += "cI";
                break;
            default:
                ret += "I";
                System.out.println("Defaulting voltage source to standard");
                break;
        }
        if (!componentLabel.getText().isEmpty()) {
            ret += ",l=" + componentLabel.getText();
        }
        ret += "]";
        return ret;
    }

    /**
     * Creates new form VoltageSourceBuilder
     */
    public CurrentSourceBuilder(String latexParams) {
        initComponents();

        parseLatexParameters(latexParams);

        setBackground(Preferences.backgroundColor);
        componentLabel.setBackground(Preferences.themeAccent);
        jLabel1.setBackground(Preferences.backgroundColor);
        jLabel2.setBackground(Preferences.backgroundColor);
        sourceSelector.setBackground(Preferences.themeAccent);

        componentLabel.setForeground(Preferences.themeText);
        jLabel1.setForeground(Preferences.themeText);
        jLabel2.setForeground(Preferences.themeText);
        sourceSelector.setForeground(Preferences.themeText);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        componentLabel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        sourceSelector = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(320, 50));

        jLabel1.setText("Label");

        jLabel2.setText("Source Type");

        sourceSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Current Source", "Controlled Current Source", " " }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(componentLabel))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sourceSelector, 0, 256, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(componentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sourceSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField componentLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> sourceSelector;
    // End of variables declaration//GEN-END:variables
}
